version: '3.7'

services:
  api:
    container_name: api
    build:
      context: .
      target: $ENV
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229
    command: yarn start:$ENV
    env_file:
      - .env
      - .env.${ENV}
    networks:
      - private-network

  postgres_db:
    container_name: postgres_db
    stdin_open: true # docker run -i
    tty: true # docker run -t 
    image: postgres
    ports:
        - '5432:5432'
    env_file:
        - .env
        - .env.${ENV}
    environment:
        - PGDATA=/var/lib/postgresql/data
    volumes:
        - postgres-data:/var/lib/postgresql/data
    networks:
        - private-network
          
networks:
  private-network:

volumes:
  postgres-data: